Repository AY1920S2-CS2103T-F11-2/main, pull requests merged in 2020-04, with the labels that each got.

#208 [GUI/UX] Fixes some PED issues
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Name.java
  src/test/java/seedu/address/model/client/ClientTest.java
Labels: status.Done

#210 Add exercise test
  src/test/java/seedu/address/logic/commands/DeleteExerciseCommandTest.java
Labels: status.Done

#209 Add redirect to FitBiz user guide for help command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: status.Done

#212 Fix code quality
  src/main/java/seedu/address/commons/trie/Node.java
  src/main/java/seedu/address/commons/trie/SimilarWordsResult.java
  src/main/java/seedu/address/commons/trie/Trie.java
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/history/CommandHistory.java
  src/main/java/seedu/address/model/CommandHistoryState.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/commons/trie/NodeTest.java
  src/test/java/seedu/address/commons/trie/TrieTest.java
  src/test/java/seedu/address/logic/history/CommandHistoryTest.java
  src/test/java/seedu/address/model/CommandHistoryStateTest.java
  src/test/java/seedu/address/storage/CommandHistoryStorageTest.java
Labels: status.Done

#213 [UG] Reorder commands to make more logical sense
  docs/UserGuide.adoc
Labels: status.Done

#217 [GUI] Conditionally display the age and gender of client
  src/main/java/seedu/address/model/client/Birthday.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Gender.java
  src/main/java/seedu/address/ui/ClientCard.java
Labels: status.Done

#216 Refactor methods and add requirenonnull
  src/main/java/seedu/address/logic/commands/AddExerciseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExerciseCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExerciseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteExerciseCommandTest.java
  src/test/java/seedu/address/testutil/ExerciseBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: severity.Low

#204 [GUI] Fix command parameters and error messages
  src/main/java/seedu/address/model/client/Birthday.java
  src/main/java/seedu/address/model/client/CurrentWeight.java
  src/main/java/seedu/address/model/client/Gender.java
  src/main/java/seedu/address/model/client/Height.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Sport.java
  src/main/java/seedu/address/model/client/TargetWeight.java
  src/main/java/seedu/address/model/exercise/ExerciseDate.java
  src/main/java/seedu/address/model/exercise/ExerciseName.java
  src/main/java/seedu/address/model/exercise/ExerciseReps.java
  src/main/java/seedu/address/model/exercise/ExerciseSets.java
  src/main/java/seedu/address/model/exercise/ExerciseWeight.java
  src/main/java/seedu/address/model/exercise/UniqueExerciseList.java
  src/test/java/seedu/address/logic/commands/ExerciseCommandTestUtil.java
  src/test/java/seedu/address/model/client/NameTest.java
  src/test/java/seedu/address/model/client/SportTest.java
  src/test/java/seedu/address/model/exercise/ExerciseDateTest.java
  src/test/java/seedu/address/model/exercise/ExerciseNameTest.java
  src/test/java/seedu/address/model/exercise/ExerciseRepsTest.java
  src/test/java/seedu/address/model/exercise/ExerciseSetsTest.java
  src/test/java/seedu/address/model/exercise/ExerciseWeightTest.java
  src/test/java/seedu/address/testutil/ExerciseBuilder.java
Labels: priority.High, status.Done, type.Enhancement

#214 [ENHANCEMENT] add-e Implementation
  src/main/java/seedu/address/logic/commands/AddExerciseCommand.java
  src/main/java/seedu/address/logic/commands/EditExerciseCommand.java
  src/main/java/seedu/address/logic/parser/EditExerciseCommandParser.java
  src/main/java/seedu/address/logic/parser/FitBizParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exercise/UniqueExerciseList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditExerciseCommandTest.java
  src/test/java/seedu/address/logic/commands/ExerciseCommandTestUtil.java
  src/test/java/seedu/address/testutil/EditExerciseDescriptorBuilder.java
Labels: priority.Medium, status.Done, type.Enhancement

#223 [DG] Fix flow and UML diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/CommandHistoryClassDiagram.puml
  docs/diagrams/CommandHistorySequenceDiagram.puml
  docs/images/CommandHistoryClassDiagram.png
  docs/images/CommandHistorySequenceDiagram.png
Labels: status.Done

#218 [GUI] Fix GUI for v1.4
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/ClientView.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ScheduleCard.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ClientView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduleCard.fxml
Labels: priority.High, status.Done

#224 [FEATURE] Add autocomplete for prefixes
  src/main/java/seedu/address/commons/trie/SimilarWordsResult.java
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddExerciseCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/commons/trie/SimilarWordsResultTest.java
Labels: status.Done, type.Enhancement

#226 Add export command and functionality
  .gitignore
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/export/Exporter.java
  src/main/java/seedu/address/logic/history/CommandHistory.java
  src/main/java/seedu/address/logic/parser/FitBizParser.java
  src/main/java/seedu/address/model/CommandHistoryState.java
  src/main/java/seedu/address/storage/StorageReaderWriter.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/export/ExporterTest.java
  src/test/java/seedu/address/logic/parser/FitBizParserTest.java
  src/test/java/seedu/address/storage/CommandHistoryStorageTest.java
Labels: status.Done

#230 [ENHANCEMENT] Improve code quality
  src/main/java/seedu/address/model/exercise/ExerciseReps.java
  src/main/java/seedu/address/model/exercise/ExerciseSets.java
  src/main/java/seedu/address/model/exercise/ExerciseWeight.java
Labels: status.Done, type.Enhancement

#232 Bug Fix
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Medium, severity.High, status.Done, type.Bug

#233 [ENHANCEMENT] Minor fixes for v1.4
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Sport.java
  src/main/java/seedu/address/model/exercise/UniqueExerciseList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/test/java/seedu/address/logic/commands/EditExerciseCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: status.Done

#234 Change app icon and Ui.png for v1.4
  docs/images/Ui.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/logo-square.png
  src/main/resources/images/logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: status.Done

#238 [REFACTOR] Improve code quality
  src/main/java/seedu/address/commons/trie/Node.java
  src/main/java/seedu/address/commons/trie/SimilarWordsResult.java
  src/main/java/seedu/address/commons/trie/Trie.java
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/export/Exporter.java
  src/main/java/seedu/address/logic/history/CommandHistory.java
  src/main/java/seedu/address/storage/StorageReaderWriter.java
Labels: status.Ongoing

#231 Add filter c
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FitBizParser.java
  src/main/java/seedu/address/model/client/TagAndSportContainsKeywordsPredicate.java
  src/test/data/JsonSerializableFitBizTest/typicalClientsFitBiz.json
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: status.Done

#239 Remove unneces method to be consistent with addexercise
  src/main/java/seedu/address/logic/commands/EditExerciseCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: status.Done

#242 Hook filter-c command to autocomplete
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
Labels: status.Done

#243 Refactor CommandHistoryStorageTest to StorageReaderWriterTest
  src/test/java/seedu/address/storage/StorageReaderWriterTest.java
Labels: status.Done

#249 [Refactor] Add getValue() to Exercise classes to reduce sore eyes
  src/main/java/seedu/address/model/exercise/ExerciseDate.java
  src/main/java/seedu/address/model/exercise/ExerciseName.java
  src/main/java/seedu/address/model/exercise/ExerciseReps.java
  src/main/java/seedu/address/model/exercise/ExerciseSets.java
  src/main/java/seedu/address/model/exercise/ExerciseWeight.java
  src/main/java/seedu/address/model/exercise/UniqueExerciseList.java
Labels: status.Done

#251 Remove fxml version warning
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/ClientView.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ExerciseListTable.fxml
  src/main/resources/view/GraphWindow.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonalBestTable.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ScheduleCard.fxml
  src/main/resources/view/SchedulePanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/resources/view/UiPartTest/validFile.fxml
Labels: status.Done

#252 Hook edit-e to personal best
  src/main/java/seedu/address/logic/commands/EditExerciseCommand.java
Labels: status.Done

#258 Fix Axis value
  src/main/java/seedu/address/model/graph/Axis.java
Labels: status.Done

#256 Refactor AutoComplete to decrease coupling
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/autocomplete/AutoCompleteResult.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/autocomplete/AutoCompleteResultTest.java
  src/test/java/seedu/address/logic/autocomplete/AutoCompleteTest.java
Labels: status.Done

#263 Storage refactor
  src/main/java/seedu/address/commons/util/ExportUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/export/Exporter.java
  src/main/java/seedu/address/logic/history/CommandHistory.java
  src/main/java/seedu/address/storage/StorageReaderWriter.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/export/ExporterTest.java
  src/test/java/seedu/address/logic/history/CommandHistoryTest.java
  src/test/java/seedu/address/storage/StorageReaderWriterTest.java
Labels: status.Done

#266 Rename AutoComplete to Autocomplete for consistency
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/autocomplete/Autocomplete.java
  src/main/java/seedu/address/logic/autocomplete/AutocompleteResult.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteResultTest.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteTest.java
Labels: status.Done

#261 Removed bug in filter-c
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/client/TagAndSportContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: status.Done

#227 [UG] list-c, add-e, edit-e
  docs/UserGuide.adoc
  docs/images/ug-addeDuplicatePart1.png
  docs/images/ug-addeDuplicatePart2.png
  docs/images/ug-addeDuplicatePart3.png
  docs/images/ug-addeExamplePart1.png
  docs/images/ug-addeExamplePart2.png
  docs/images/ug-addeExamplePart3.png
  docs/images/ug-editeDuplicatePart1.png
  docs/images/ug-editeDuplicatePart2.png
  docs/images/ug-editeDuplicatePart3.png
  docs/images/ug-editeExamplePart1.png
  docs/images/ug-editeExamplePart2.png
  docs/images/ug-editeExamplePart3.png
  docs/images/ug-findcExamplePart1.png
  docs/images/ug-findcExamplePart2.png
  docs/images/ug-findcExamplePart3.png
  docs/images/ug-findcIncompleteNamePart1.png
  docs/images/ug-findcIncompleteNamePart2.png
  docs/images/ug-findcIncompleteNamePart3.png
  docs/images/ug-findcMultiplePart1.png
  docs/images/ug-findcMultiplePart2.png
Labels: status.Done

#246 [DG] Update storage class diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: status.Done

#247 [DG] Update DG (Zi Ying)
  docs/DeveloperGuide.adoc
  docs/diagrams/GraphClassDiagram.puml
  docs/diagrams/GraphCommandActivityDiagram.puml
  docs/diagrams/GraphSequenceDiagram.puml
  docs/diagrams/PersonalBestClassDiagram.puml
  docs/diagrams/PersonalBestSequenceDiagram.puml
  docs/images/GraphClassDiagram.png
  docs/images/GraphCommandActivityDiagram.png
  docs/images/GraphSequenceDiagram.png
  docs/images/PersonalBestClassDiagram.png
  docs/images/PersonalBestSequenceDiagram.png
Labels: status.Done

#248 DG kerwei
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ViewSequenceDiagram.png
  docs/images/checkstyle-idea-configuration.png
Labels: status.Done

#262 [DG] Exercise Implementation
  docs/DeveloperGuide.adoc
  docs/diagrams/AddExerciseCommandSequenceDiagram.puml
  docs/diagrams/AddExerciseCommandSequenceDiagramPart2.puml
  docs/diagrams/AddExerciseCommandSequenceDiagramPart3.puml
  docs/diagrams/ExerciseClassDiagram.puml
  docs/diagrams/ExerciseCommandsActivityDiagram.puml
  docs/images/AddExerciseCommandSequenceDiagram.png
  docs/images/AddExerciseCommandSequenceDiagramPart2.png
  docs/images/AddExerciseCommandSequenceDiagramPart3.png
  docs/images/ExerciseClassDiagram.png
  docs/images/ExerciseCommandActivityDiagram.png
  docs/images/IsSameExerciseObjectDiagram.png
Labels: status.Done

#264 [DG] UI Component
  docs/DeveloperGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: status.Done

#267 [UG] Aaron (export, autocomplete, history)
  docs/UserGuide.adoc
  docs/images/Ui-annotated.png
  docs/images/Ui-annotated.xcf
  docs/images/autocomplete-1.png
  docs/images/autocomplete-2.png
  docs/images/command-history-hello-world.png
  docs/images/command-history-unknown-command.png
  docs/images/delete-e-1.png
  docs/images/delete-e-2.png
  docs/images/delete-e-3.png
  docs/images/export-1.png
  docs/images/export-2.png
  docs/images/export-3.png
  docs/images/export-4.png
Labels: status.Done

#244 [DG] Update DG (Aaron)
  docs/DeveloperGuide.adoc
  docs/diagrams/CommandAutocompleteClassDiagram.puml
  docs/diagrams/CommandAutocompleteSequenceDiagram.puml
  docs/diagrams/CommandAutocompleteSequenceDiagramRef.puml
  docs/diagrams/CommandHistoryClassDiagram.puml
  docs/diagrams/CommandHistorySequenceDiagram.puml
  docs/images/CommandAutocompleteActivityDiagram.png
  docs/images/CommandAutocompleteClassDiagram.png
  docs/images/CommandAutocompleteSequenceDiagram.png
  docs/images/CommandAutocompleteSequenceDiagramRef.png
  docs/images/CommandHistoryClassDiagram.png
  docs/images/CommandHistorySequenceDiagram.png
Labels: status.Done

#260 [UG] update Ker Wei
  docs/UserGuide.adoc
  docs/images/AddAddressSuccess.png
  docs/images/AddExampleCommand.png
  docs/images/AddExampleSuccess.png
  docs/images/AddNoAddress.png
  docs/images/AddNoAddressError.png
  docs/images/AddSameEmailCommand.png
  docs/images/AddSameEmailError.png
  docs/images/AddWithAddressCommand.png
  docs/images/FilterExampleCommand.png
  docs/images/FilterExampleSuccess.png
  docs/images/FilterTagCommand.png
  docs/images/FilterTagCorrectCommand.png
  docs/images/FilterTagError.png
  docs/images/FilterTagSuccess.png
Labels: status.Done

#273 [UG ]Update incorrect diagram
  docs/images/FilterTagCorrectCommand.png
Labels: status.Done

#272 [DG] update kw
  docs/DeveloperGuide.adoc
  docs/diagrams/FilterClassDiagram.puml
  docs/images/FilterClassDiagram.png
Labels: status.Done

#276 [DG] Update diagrams and labels
  docs/DeveloperGuide.adoc
  docs/diagrams/GraphSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/GraphSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: status.Done

#270 [UG] view-c, delete-c, graph (ZY)
  docs/UserGuide.adoc
  docs/images/ug-delete-1.png
  docs/images/ug-delete-2.png
  docs/images/ug-delete-3.png
  docs/images/ug-delete-4.png
  docs/images/ug-graph-1.png
  docs/images/ug-graph-10.png
  docs/images/ug-graph-2.png
  docs/images/ug-graph-3.png
  docs/images/ug-graph-4.png
  docs/images/ug-graph-5.png
  docs/images/ug-graph-6.png
  docs/images/ug-graph-7.png
  docs/images/ug-graph-8.png
  docs/images/ug-graph-9.png
  docs/images/ug-view-1.png
  docs/images/ug-view-2.png
  docs/images/ug-view-3.png
  docs/images/ug-view-4.png
Labels: status.Done

#271 [PPP/DG/UG/CODE] Fixes to everything
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CommandAutocompleteActivityDiagram.puml
  docs/images/CommandAutocompleteActivityDiagram.png
  docs/images/export-2.png
  docs/team/aaroncql.adoc
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/test/java/seedu/address/logic/autocomplete/AutocompleteTest.java
Labels: status.Ongoing

#278 Include project portfolio in About Us
  docs/AboutUs.adoc
  docs/stylesheets/gh-pages.css
Labels: status.Done

#280 Add glossary to appendix
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.Done

#279 Refactor JsonSerializableFitBiz to JsonSerializableFitBizStorage
  src/main/java/seedu/address/storage/JsonFitBizStorage.java
  src/main/java/seedu/address/storage/JsonSerializableFitBizStorage.java
  src/test/data/JsonSerializableFitBizStorageTest/duplicateClientFitBiz.json
  src/test/data/JsonSerializableFitBizStorageTest/invalidClientFitBiz.json
  src/test/data/JsonSerializableFitBizStorageTest/typicalClientsFitBiz.json
  src/test/java/seedu/address/storage/JsonSerializableFitBizStorageTest.java
Labels: status.Done

#281 [PPP] Ker Wei
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/tohkerwei.adoc
Labels: status.Done

#283 Tweak diagrams to follow DG
  docs/diagrams/CommandAutocompleteSequenceDiagram.puml
  docs/diagrams/CommandAutocompleteSequenceDiagramRef.puml
  docs/diagrams/CommandHistorySequenceDiagram.puml
  docs/images/CommandAutocompleteSequenceDiagram.png
  docs/images/CommandAutocompleteSequenceDiagramRef.png
  docs/images/CommandHistorySequenceDiagram.png
Labels: status.Done

#285 Fix class diagrams
  docs/diagrams/CommandHistorySequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/CommandHistorySequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: status.Done

#284 [DG] Edit appendix
  docs/DeveloperGuide.adoc
Labels: status.Done

#277 [DG] Add manual testing and fixes
  docs/DeveloperGuide.adoc
Labels: status.Done

#236 [ENHANCEMENT] Update command summary
  docs/UserGuide.adoc
Labels: status.Done

#287 [DG] update filter class diagram
  docs/images/FilterClassDiagram.png
Labels: status.Done

#286 Fix english
  docs/DeveloperGuide.adoc
  docs/diagrams/AddExerciseCommandSequenceDiagram.puml
  docs/images/AddExerciseCommandSequenceDiagram.png
Labels: status.Done

#265 [PPP] Yonggiee
  docs/team/Yonggiee.adoc
Labels: status.Ongoing

#282 [PPP] Zi Ying
  docs/DeveloperGuide.adoc
  docs/UmlSubmission_ZY.adoc
  docs/UserGuide.adoc
  docs/team/ziyingli.adoc
Labels: status.Done

#299 Fix DG
  docs/DeveloperGuide.adoc
Labels: status.Done

#297 [UG] Fix formatting
  docs/UserGuide.adoc
Labels: status.Done

#302 [UG] Fix overview and quickstart
  docs/UserGuide.adoc
Labels: status.Done

#304 [UG] Fix export, delete-e, and help commands
  docs/UserGuide.adoc
  docs/images/autocomplete-1.png
  docs/images/autocomplete-1.xcf
  docs/images/autocomplete-2.png
  docs/images/autocomplete-2.xcf
  docs/images/command-history-hello-world.png
  docs/images/command-history-hello-world.xcf
  docs/images/command-history-unknown-command.png
  docs/images/command-history-unknown-command.xcf
  docs/images/delete-e-1.png
  docs/images/delete-e-1.xcf
  docs/images/delete-e-2.png
  docs/images/delete-e-2.xcf
  docs/images/delete-e-3.png
  docs/images/delete-e-3.xcf
  docs/images/export-1.png
  docs/images/export-1.xcf
  docs/images/export-2.png
  docs/images/export-2.xcf
  docs/images/export-3.png
  docs/images/export-3.xcf
Labels: status.Done

#305 [UG] Fix view-c, delete-c and graph
  docs/UserGuide.adoc
Labels: status.Done

#303 [UG] YJ part + command summary changes
  docs/UserGuide.adoc
  docs/images/ug-addeDuplicatePart1.png
  docs/images/ug-addeDuplicatePart2.png
  docs/images/ug-addeDuplicatePart3.png
  docs/images/ug-addeExamplePart1.png
  docs/images/ug-addeExamplePart2.png
  docs/images/ug-addeExamplePart3.png
  docs/images/ug-editeDuplicatePart1.png
  docs/images/ug-editeDuplicatePart2.png
  docs/images/ug-editeDuplicatePart3.png
  docs/images/ug-findcIncompleteNamePart2.png
  docs/images/ug-findcIncompleteNamePart3.png
  docs/images/ug-findcMultiple.png
  docs/images/ug-findcMultiplePart1.png
Labels: status.Done

#309 [UG] Minor fix + cover page
  docs/UserGuide.adoc
  docs/images/delete-e-3.png
  docs/images/delete-e-3.xcf
  docs/images/logo.png
Labels: status.Done

#308 UG ML
  docs/UserGuide.adoc
  docs/images/UGEditCDiagram1.png
  docs/images/UGEditCDiagram2.png
  docs/images/UGEditCDiagram3.png
  docs/images/UGEditCDiagram4.png
  docs/images/UGListCDiagram0.png
  docs/images/UGListCDiagram1.png
  docs/images/UGListCDiagram2.png
  docs/images/UGListCDiagram3.png
  docs/images/UGListCDiagram4.png
  docs/images/UGListCDiagram5.png
  docs/images/UGScheduleDiagram1.png
  docs/images/UGScheduleDiagram2.png
  docs/images/UGScheduleDiagram3.png
  docs/images/UGScheduleDiagram4.png
  docs/images/UGScheduleDiagram5.png
  docs/images/UGScheduleDiagram6.png
  docs/images/UGScheduleDiagram7.png
  docs/images/UGScheduleDiagram8.png
Labels: status.Done
